### ISSUE TITLE
Fix compat with SciMLBase 2.11

### ISSUE THREAD

**Issue by hexaeder** [JuliaDynamics/NetworkDynamics.jl#132]
https://github.com/SciML/SymbolicIndexingInterface.jl

is the way to go to access symbols moving forward. would resolve the restriction introduced in #131

**Comment by Datseris** [comment]
Hi @hexaeder can you please tell me how you learned of this package? I am trying to follow this as I also use symbolic indexing but I haven't heard of this package yet. Are there some specific channels you follow? E.g., this isn't posted in `diffeq-bridged` on slack.

**Comment by hexaeder** [comment]
Well nothing of that sort, I just realized that it broke my docs in GraphMakie where I use NetworkDynamics and I was able to track it down to this [SciMLBase-PR](https://github.com/SciML/SciMLBase.jl/pull/532#issuecomment-1857727420) which altered the struct definition 3 days ago and asked there...  Chris also posted a link to [the docs of the new package](https://docs.sciml.ai/SymbolicIndexingInterface/stable/api/) there.

I think it's inevitable, the core mechanism of NetworkDynamics was written many years ago when the SciML ecosystem was in a completely different shape. Luckily next year we'll have funding to do a proper rework and hopefully get rid of those kind of hacks :)

**Comment by hexaeder** [comment]
fixed in #140
