### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by lindnemi** [JuliaDynamics/NetworkDynamics.jl#40]
This is more of a long term research issue. How much can network_dynamics benefit from parallelizing the core loop (depending on system size)? And how to implement the GPU kernels?

See how far we get with https://github.com/JuliaGPU/CuArrays.jl, then try https://juliagpu.gitlab.io/KernelAbstractions.jl/ (former GPUifyLoops) and do some benchmarks comparing a GPU version to a`@threads` parallelized version.

**Comment by hexaeder** [comment]
closed by #140
