### ISSUE TITLE
Make doctests part of testing

### ISSUE THREAD

**Issue by hexaeder** [JuliaDynamics/NetworkDynamics.jl#62]
I think it would be nice to have the examples in the documentation based on [Literate.jl](https://fredrikekre.github.io/Literate.jl/v2/)

I have no experience on how to set up the pipeline but in theory it would allow the to include all the examples in `runtests.jl` (or maybe better `doctests.jl`) and test whether the code in the documentation actually runs with the current version of the package.

**Comment by lindnemi** [comment]
I agree that it would be nice, though it means learning the syntax and rewriting a bunch of scripts. 

At the moment all the code in the docs is wrapped in `@example` blocks and gets tested when the documentation is build, now i'm trying to figure out how to include it in the packages' tests.

**Comment by hexaeder** [comment]
Oh okay I didn't know about the doctests! It seems like they just print out a warning if they fail though, leaving a big green :heavy_check_mark: in the PR.

I'll close this issue because it has nothing todo with `Literate.jl` anymore. I might be good to open general Issue concerning the document-ci: when and where should the build command run, when and where should it publish an new version, what are the rules on fail/success.

**Comment by lindnemi** [comment]
Pasting from slack:

> Hi. I have a bunch of @example blocks in my .md files. I would like to include those in the Tests of the package. I tried to use the doctest function but it immediately returned 1 Passed Test result, so it couldn't have run all the blocks. What's the right way to do this?

> You could perhaps include hidden code that does the testing and test it by making sure the build passes.

**Comment by lindnemi** [comment]
i guess it would be enough if the workflow fails in case one of the @example blocks errors

**Comment by hexaeder** [comment]
I've looked into this: it is possible to [pass the option `strict` to the `makedocs` command](https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.makedocs).
However this also means
